AdventureWorks_2022:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: DESKTOP-RC4C5PQ\SQL2022
      port: 1433
      database: AdventureWorks2022
      schema: dbo
      windows_login: True
      trust_cert: True